name: CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/flask-redis:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Set kubernetes context
        uses: azure/k8s-set-context@v3
        with:
          method: service-account
          k8s-url: https://72ad2064-31b4-4552-a630-c88487140b6f.k8s.ondigitalocean.com
          k8s-secret: ${{ secrets.KUBERNETES_SECRET }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        id: install

      - name: Deploy to the Kubernetes cluster
        uses: azure/k8s-deploy@v4
        with:
          namespace: dev
          manifests: |
            kubernetes/flask.yaml
          images: |
            ghcr.io/badri/flask-redis-cd/flask-redis:${{ github.sha }}
